/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author LENOVO
 */
import ClassDAO.DAOBookingDetail;
import ClassDAO.DAOLangganan;
import MainClass.Booking;
<<<<<<< HEAD
import MainClass.Langganan;
=======
import MainClass.Jadwal;
>>>>>>> 7098e029020952d715f552b728038ec4efbd7583
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.time.Duration;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
<<<<<<< HEAD
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
=======
>>>>>>> 7098e029020952d715f552b728038ec4efbd7583

public class HistoryFrame extends javax.swing.JFrame {
    private Dashboard parent;
    /**
     * Creates new form HistoryFrame
     */
    public HistoryFrame(String id_Pengguna, Dashboard parent) {
        this.parent = parent;
        initComponents();
        loadBookingHistory(id_Pengguna);
        setLocationRelativeTo(null); // Center the frame on the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORY BOOKING");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/history.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/history.png"))); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel4)
                .addContainerGap(471, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap(420, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(backBtn)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBtn)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void loadBookingHistory(String id_Pengguna) {

        List<Booking> bookingHistory = new DAOBookingDetail().getBookingDetail(id_Pengguna);
        DAOLangganan daoLangganan = new DAOLangganan();

        jPanel2.removeAll();
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        
        if (bookingHistory != null && !bookingHistory.isEmpty()) {
<<<<<<< HEAD
            for (Booking booking : bookingHistory) {               
                
                if (booking == null || booking.getJadwal() == null || booking.getJadwal().isEmpty() 
                    || booking.getLapangan() == null) {
                    continue;
=======
            for (Booking booking : bookingHistory) {
                
                if (booking == null || booking.getJadwal() == null || booking.getJadwal().isEmpty() 
                    || booking.getLapangan() == null) {
                    continue; // skip data yang ga valid
>>>>>>> 7098e029020952d715f552b728038ec4efbd7583
                }
                
                JPanel bookingPanel = new JPanel();
                bookingPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
                bookingPanel.setBackground(new Color(255, 255, 255));
                bookingPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
                bookingPanel.setMaximumSize(new Dimension(570, 150));
                
                

                

                
                if (booking.getJadwal() != null && !booking.getJadwal().isEmpty()) {
                    Duration duration = Duration.between(
                        booking.getClassJadwal().getJam_Mulai(), 
                        booking.getClassJadwal().getJam_Selesai()
                    );
                    long toHours = duration.toHours();

                    Langganan jenisLangganan = daoLangganan.LoadSomeById(booking.getPengguna().getJenis_langganan());

                    double hargaAwal = booking.getLapangan().getHarga() * toHours;
                    double potongan = jenisLangganan.getPotongan() * hargaAwal;
                    double hargaAkhir = hargaAwal - potongan;

                    String bookingDetails = String.format("""
                        <html>
                            <p>Nama Lapangan: %s</p>
                            <p>Location: %s</p>
                            <p>Olahraga: %s</p>
                            <p>Tanggal: %s</p>
                            <p>Durasi: %d jam</p>
                            <p>Harga: %s</p>
                        </html>
                        """,
                        booking.getLapangan().getNama_lapangan(),
                        booking.getLapangan().getLokasi(),
                        booking.getLapangan().getOlahraga().getNama_olahraga(),
                        booking.getClassJadwal().getTanggal().toString(),
                        toHours,
                        hargaAkhir
                    );

                    JLabel detailsLabel = new JLabel(bookingDetails);
                    detailsLabel.setFont(new Font("Poppins", Font.PLAIN, 14));
                    bookingPanel.add(detailsLabel);
                    jPanel2.add(bookingPanel);
                    jPanel2.add(Box.createVerticalStrut(10));
                } else {
                    
                    JLabel warning = new JLabel("Booking ini tidak memiliki jadwal.");
                    warning.setFont(new Font("Poppins", Font.ITALIC, 12));
                    bookingPanel.add(warning);
                    jPanel2.add(bookingPanel);
                    jPanel2.add(Box.createVerticalStrut(10));
                }
            }
        } else {
            
            JLabel noBookingsLabel = new JLabel("No booking details found for the user.");
            noBookingsLabel.setFont(new Font("Poppins", Font.PLAIN, 14));
            jPanel2.add(noBookingsLabel);
        }

        
        // jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK)); // Debug border
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
