/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ClassDAO.DAOJadwal;
import MainClass.Jadwal;
import MainClass.Pemilik;
import java.awt.CardLayout;
import MainClass.Lapangan;
import com.formdev.flatlaf.FlatLightLaf;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.UIManager;
import ClassDAO.DAOLapangan;

/**
 *
 * @author benja
 */
public class KelolaLapangan extends javax.swing.JFrame {

    private ArrayList<javax.swing.JToggleButton> jadwalButtons;
    private ArrayList<String> jadwalLabels;
    private DAOJadwal daojadwal = new DAOJadwal();
    private Lapangan lapangan;
    private DAOLapangan daolapangan = new DAOLapangan();
    private Pemilik pemilik;

    /**
     * Creates new form KelolaLapangan
     */
    public KelolaLapangan() {
        initComponents();
        addJadwalButtonListeners();
    }

    public KelolaLapangan(Lapangan lapangan, Pemilik pemilik) {
        this.pemilik = pemilik;
        this.lapangan = lapangan;
        initComponents();
        setLocationRelativeTo(null);
        addJadwalButtonListeners();

        jadwalButtons = new ArrayList<>(Arrays.asList(
                btnJadwalTujuh, btnJadwalDelapan, btnJadwalSembilan, btnJadwalSepuluh,
                btnJadwalSebelas, btnJadwalDuabelas, btnJadwalTigabelas, btnJadwalEmpatbelas,
                btnJadwalLimabelas, btnJadwalEnambelas, btnJadwalTujuhbelas, btnJadwalDelapanbelas,
                btnJadwalSembilanbelas, btnJadwalDuapuluh, btnJadwalDuapuluhSatu, btnJadwalDuapuluhDua,
                btnJadwalDuapuluhTiga));
        jadwalLabels = new ArrayList<>(Arrays.asList(
                "07:00-08:00", "08:00-09:00", "09:00-10:00", "10:00-11:00",
                "11:00-12:00", "12:00-13:00", "13:00-14:00", "14:00-15:00",
                "15:00-16:00", "16:00-17:00", "17:00-18:00", "18:00-19:00",
                "19:00-20:00", "20:00-21:00", "21:00-22:00", "22:00-23:00", "23:00-00:00"));

        tanggal.addDateChangeListener(e -> {
            // Aktifkan semua tombol dulu sebelum disable ulang
            for (javax.swing.JToggleButton btn : jadwalButtons) {
                btn.setEnabled(true);
                btn.setSelected(false); // opsional: reset pilihan
            }
            if (tanggal.getDate() != null) {
                disableBookedSlots(lapangan.getId_lapangan(), tanggal.getDate());
            }
        });
    }

    private void disableBookedSlots(String idLapangan, LocalDate tanggal) {
        ArrayList<Jadwal> jadwalList = daojadwal.getJadwalByLapangan(idLapangan, tanggal);
        for (Jadwal jadwal : jadwalList) {
            int start = jadwal.getJam_Mulai().getHour();
            int end = jadwal.getJam_Selesai().getHour();
            for (int jam = start; jam < end; jam++) {
                int idx = jam - 7;
                if (idx >= 0 && idx < jadwalButtons.size()) {
                    jadwalButtons.get(idx).setEnabled(false);
                }
            }
        }
        setLocationRelativeTo(null);
    }
    
    private void pesanUbahStatus(){
        javax.swing.JOptionPane.showMessageDialog(this, "Berhasil mengubah status lapangan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelKelolaLapangan = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        btnMatikanJadwal = new javax.swing.JButton();
        btnUbahStatus = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        panelMatikanJadwal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tanggal = new com.github.lgooddatepicker.components.DatePicker();
        btnJadwalTujuh = new javax.swing.JToggleButton();
        btnJadwalDelapan = new javax.swing.JToggleButton();
        btnJadwalSembilan = new javax.swing.JToggleButton();
        btnJadwalSepuluh = new javax.swing.JToggleButton();
        btnJadwalSebelas = new javax.swing.JToggleButton();
        btnJadwalDuabelas = new javax.swing.JToggleButton();
        btnJadwalTigabelas = new javax.swing.JToggleButton();
        btnJadwalEmpatbelas = new javax.swing.JToggleButton();
        btnJadwalLimabelas = new javax.swing.JToggleButton();
        btnJadwalEnambelas = new javax.swing.JToggleButton();
        btnJadwalTujuhbelas = new javax.swing.JToggleButton();
        btnJadwalDelapanbelas = new javax.swing.JToggleButton();
        btnJadwalSembilanbelas = new javax.swing.JToggleButton();
        btnJadwalDuapuluh = new javax.swing.JToggleButton();
        btnJadwalDuapuluhSatu = new javax.swing.JToggleButton();
        btnJadwalDuapuluhDua = new javax.swing.JToggleButton();
        btnJadwalDuapuluhTiga = new javax.swing.JToggleButton();
        labelJadwalYangDipilih = new javax.swing.JLabel();
        btnNonaktifkanJadwal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAlasan = new javax.swing.JTextField();
        panelUbahStatusLapangan = new javax.swing.JPanel();
        judul2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnBuka = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        btnMaintenance = new javax.swing.JButton();
        panelLaporan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(0, 153, 102));

        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("Kelola Lapangan");
        judul.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnMatikanJadwal.setText("Nonaktifkan Jadwal");
        btnMatikanJadwal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMatikanJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatikanJadwalActionPerformed(evt);
            }
        });

        btnUbahStatus.setText("Ubah Status Lapangan");
        btnUbahStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnUbahStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahStatusActionPerformed(evt);
            }
        });

        btnLaporan.setText("Lihat Laporan Pemesanan Lapangan");
        btnLaporan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKelolaLapanganLayout = new javax.swing.GroupLayout(panelKelolaLapangan);
        panelKelolaLapangan.setLayout(panelKelolaLapanganLayout);
        panelKelolaLapanganLayout.setHorizontalGroup(
            panelKelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelKelolaLapanganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKelolaLapanganLayout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnLaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addComponent(btnUbahStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMatikanJadwal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelKelolaLapanganLayout.setVerticalGroup(
            panelKelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKelolaLapanganLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnMatikanJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUbahStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(panelKelolaLapangan, "cardKelola");

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pilih Jadwal");
        jLabel1.setBackground(new java.awt.Color(0, 153, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        tanggal.setText("Pilih Tanggal");

        btnJadwalTujuh.setText("07:00-08:00");
        btnJadwalTujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalTujuhActionPerformed(evt);
            }
        });

        btnJadwalDelapan.setText("08:00-09:00");
        btnJadwalDelapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalDelapanActionPerformed(evt);
            }
        });

        btnJadwalSembilan.setText("09:00-10:00");
        btnJadwalSembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalSembilanActionPerformed(evt);
            }
        });

        btnJadwalSepuluh.setText("10:00-11:00");
        btnJadwalSepuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalSepuluhActionPerformed(evt);
            }
        });

        btnJadwalSebelas.setText("11:00-12:00");
        btnJadwalSebelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalSebelasActionPerformed(evt);
            }
        });

        btnJadwalDuabelas.setText("12:00-13:00");
        btnJadwalDuabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalDuabelasActionPerformed(evt);
            }
        });

        btnJadwalTigabelas.setText("13:00-14:00");
        btnJadwalTigabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalTigabelasActionPerformed(evt);
            }
        });

        btnJadwalEmpatbelas.setText("14:00-15:00");
        btnJadwalEmpatbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalEmpatbelasActionPerformed(evt);
            }
        });

        btnJadwalLimabelas.setText("15:00-16:00");
        btnJadwalLimabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalLimabelasActionPerformed(evt);
            }
        });

        btnJadwalEnambelas.setText("16:00-17:00");
        btnJadwalEnambelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalEnambelasActionPerformed(evt);
            }
        });

        btnJadwalTujuhbelas.setText("17:00-18:00");
        btnJadwalTujuhbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalTujuhbelasActionPerformed(evt);
            }
        });

        btnJadwalDelapanbelas.setText("18:00-19:00");
        btnJadwalDelapanbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalDelapanbelasActionPerformed(evt);
            }
        });

        btnJadwalSembilanbelas.setText("19:00-20:00");
        btnJadwalSembilanbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalSembilanbelasActionPerformed(evt);
            }
        });

        btnJadwalDuapuluh.setText("20:00-21:00");
        btnJadwalDuapuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalDuapuluhActionPerformed(evt);
            }
        });

        btnJadwalDuapuluhSatu.setText("21:00-22:00");
        btnJadwalDuapuluhSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalDuapuluhSatuActionPerformed(evt);
            }
        });

        btnJadwalDuapuluhDua.setText("22:00-23:00");
        btnJadwalDuapuluhDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalDuapuluhDuaActionPerformed(evt);
            }
        });

        btnJadwalDuapuluhTiga.setText("23:00-00:00");
        btnJadwalDuapuluhTiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalDuapuluhTigaActionPerformed(evt);
            }
        });

        labelJadwalYangDipilih.setText("Jadwal dipilih: ");
        labelJadwalYangDipilih.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnNonaktifkanJadwal.setText("Nonaktifkan Jadwal Dipilih");
        btnNonaktifkanJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNonaktifkanJadwalActionPerformed(evt);
            }
        });

        jLabel2.setText("Alasan (Optional)");

        txtAlasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlasanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMatikanJadwalLayout = new javax.swing.GroupLayout(panelMatikanJadwal);
        panelMatikanJadwal.setLayout(panelMatikanJadwalLayout);
        panelMatikanJadwalLayout.setHorizontalGroup(
            panelMatikanJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMatikanJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                        .addComponent(txtAlasan, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNonaktifkanJadwal))
                    .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelMatikanJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelJadwalYangDipilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)))
                    .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                        .addGroup(panelMatikanJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                                .addComponent(btnJadwalTujuh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnJadwalDelapan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnJadwalSembilan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnJadwalSepuluh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnJadwalSebelas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnJadwalDuabelas))
                            .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                                .addGroup(panelMatikanJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                                        .addComponent(btnJadwalSembilanbelas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnJadwalDuapuluh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnJadwalDuapuluhSatu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnJadwalDuapuluhDua))
                                    .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                                        .addComponent(btnJadwalTigabelas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnJadwalEmpatbelas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnJadwalLimabelas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnJadwalEnambelas)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelMatikanJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                                        .addComponent(btnJadwalTujuhbelas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnJadwalDelapanbelas))
                                    .addComponent(btnJadwalDuapuluhTiga))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMatikanJadwalLayout.setVerticalGroup(
            panelMatikanJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panelMatikanJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJadwalTujuh)
                    .addComponent(btnJadwalDelapan)
                    .addComponent(btnJadwalSembilan)
                    .addComponent(btnJadwalSepuluh)
                    .addComponent(btnJadwalSebelas)
                    .addComponent(btnJadwalDuabelas))
                .addGap(18, 18, 18)
                .addGroup(panelMatikanJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJadwalTigabelas)
                    .addComponent(btnJadwalEmpatbelas)
                    .addComponent(btnJadwalLimabelas)
                    .addComponent(btnJadwalEnambelas)
                    .addComponent(btnJadwalTujuhbelas)
                    .addComponent(btnJadwalDelapanbelas))
                .addGap(18, 18, 18)
                .addGroup(panelMatikanJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJadwalSembilanbelas)
                    .addComponent(btnJadwalDuapuluh)
                    .addComponent(btnJadwalDuapuluhSatu)
                    .addComponent(btnJadwalDuapuluhDua)
                    .addComponent(btnJadwalDuapuluhTiga))
                .addGap(30, 30, 30)
                .addComponent(labelJadwalYangDipilih, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMatikanJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnNonaktifkanJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelMatikanJadwalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlasan)))
                .addGap(6, 6, 6))
        );

        mainPanel.add(panelMatikanJadwal, "cardMatikanJadwal");

        judul2.setBackground(new java.awt.Color(0, 153, 102));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ubah Status Lapangan");

        javax.swing.GroupLayout judul2Layout = new javax.swing.GroupLayout(judul2);
        judul2.setLayout(judul2Layout);
        judul2Layout.setHorizontalGroup(
            judul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judul2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
        );
        judul2Layout.setVerticalGroup(
            judul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judul2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnBuka.setBackground(new java.awt.Color(153, 255, 153));
        btnBuka.setText("Buka");
        btnBuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukaActionPerformed(evt);
            }
        });

        btnTutup.setBackground(new java.awt.Color(255, 102, 102));
        btnTutup.setText("Tutup");
        btnTutup.setToolTipText("");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        btnMaintenance.setBackground(new java.awt.Color(204, 204, 0));
        btnMaintenance.setText("Maintenance");
        btnMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintenanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUbahStatusLapanganLayout = new javax.swing.GroupLayout(panelUbahStatusLapangan);
        panelUbahStatusLapangan.setLayout(panelUbahStatusLapanganLayout);
        panelUbahStatusLapanganLayout.setHorizontalGroup(
            panelUbahStatusLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUbahStatusLapanganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUbahStatusLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMaintenance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelUbahStatusLapanganLayout.setVerticalGroup(
            panelUbahStatusLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUbahStatusLapanganLayout.createSequentialGroup()
                .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnBuka, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        mainPanel.add(panelUbahStatusLapangan, "cardUbahStatus");

        javax.swing.GroupLayout panelLaporanLayout = new javax.swing.GroupLayout(panelLaporan);
        panelLaporan.setLayout(panelLaporanLayout);
        panelLaporanLayout.setHorizontalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        panelLaporanLayout.setVerticalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        mainPanel.add(panelLaporan, "cardLaporan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukaActionPerformed
        daolapangan.updateStatus(lapangan, "buka");
        pesanUbahStatus();
        pindahCard("cardKelola");
    }//GEN-LAST:event_btnBukaActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        daolapangan.updateStatus(lapangan, "tutup");
        pesanUbahStatus();
        pindahCard("cardKelola");
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintenanceActionPerformed
        daolapangan.updateStatus(lapangan, "maintenance");
        pesanUbahStatus();
        pindahCard("cardKelola");
    }//GEN-LAST:event_btnMaintenanceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Dashboard_Pemilik dpl = new Dashboard_Pemilik(pemilik);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNonaktifkanJadwalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNonaktifkanJadwalActionPerformed
        ArrayList<Jadwal> jadwals = new ArrayList<>();
        LocalDate tgl = tanggal.getDate();
        String alasan = txtAlasan.getText();

        // Loop semua tombol, jika dipilih, buat objek Jadwal dan tambahkan ke list
        for (int i = 0; i < jadwalButtons.size(); i++) {
            if (jadwalButtons.get(i).isSelected()) {
                // Ambil jam mulai dan selesai dari label
                String[] jam = jadwalLabels.get(i).split("-");
                java.time.LocalTime jamMulai = java.time.LocalTime.parse(jam[0]);
                java.time.LocalTime jamSelesai = java.time.LocalTime.parse(jam[1]);
                Jadwal jadwal = new Jadwal(
                        null, // id_Jadwal tidak perlu diisi untuk nonaktifkan
                        tgl,
                        jamMulai,
                        jamSelesai,
                        this.lapangan
                );
                jadwals.add(jadwal);
            }
        }

        // Loop dan nonaktifkan
        for (Jadwal jadwal : jadwals) {
            daojadwal.MatikanJadwal(jadwal, alasan);
        }
        // Optional: tampilkan pesan sukses
        javax.swing.JOptionPane.showMessageDialog(this, "Jadwal berhasil dinonaktifkan.");
        // Kembali ke panel utama
        pindahCard("cardKelola");
    }// GEN-LAST:event_btnNonaktifkanJadwalActionPerformed

    private void txtAlasanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAlasanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtAlasanActionPerformed

    private void btnMatikanJadwalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMatikanJadwalActionPerformed
        pindahCard("cardMatikanJadwal");
    }// GEN-LAST:event_btnMatikanJadwalActionPerformed

    private void pindahCard(String cardName) {
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, cardName);
    }

    private void addJadwalButtonListeners() {
        javax.swing.JToggleButton[] jadwalButtons = {
                btnJadwalTujuh, btnJadwalDelapan, btnJadwalSembilan, btnJadwalSepuluh, btnJadwalSebelas,
                btnJadwalDuabelas,
                btnJadwalTigabelas, btnJadwalEmpatbelas, btnJadwalLimabelas, btnJadwalEnambelas, btnJadwalTujuhbelas,
                btnJadwalDelapanbelas,
                btnJadwalSembilanbelas, btnJadwalDuapuluh, btnJadwalDuapuluhSatu, btnJadwalDuapuluhDua,
                btnJadwalDuapuluhTiga
        };
        String[] jadwalLabels = {
                "07:00-08:00", "08:00-09:00", "09:00-10:00", "10:00-11:00", "11:00-12:00", "12:00-13:00",
                "13:00-14:00", "14:00-15:00", "15:00-16:00", "16:00-17:00", "17:00-18:00", "18:00-19:00",
                "19:00-20:00", "20:00-21:00", "21:00-22:00", "22:00-23:00", "23:00-00:00"
        };
        for (javax.swing.JToggleButton btn : jadwalButtons) {
            btn.addActionListener(e -> updateLabelJadwal(jadwalButtons, jadwalLabels));
        }
    }

    private void updateLabelJadwal(javax.swing.JToggleButton[] buttons, String[] labels) {
        java.util.List<Integer> selected = new java.util.ArrayList<>();
        for (int i = 0; i < buttons.length; i++) {
            if (buttons[i].isSelected()) {
                selected.add(i);
            }
        }
        java.util.Collections.sort(selected);

        StringBuilder sb = new StringBuilder();
        int i = 0;
        while (i < selected.size()) {
            int start = selected.get(i);
            int end = start;
            // Gabungkan yang berurutan
            while (i + 1 < selected.size() && selected.get(i + 1) == end + 1) {
                end = selected.get(i + 1);
                i++;
            }
            if (sb.length() > 0) {
                sb.append(", ");
            }
            String startLabel = labels[start].substring(0, 5);
            String endLabel = labels[end].substring(6, 11);
            sb.append(startLabel).append("-").append(endLabel);
            i++;
        }
        if (sb.length() == 0) {
            labelJadwalYangDipilih.setText("Jadwal dipilih: ");
        } else {
            labelJadwalYangDipilih.setText("Jadwal dipilih: " + sb.toString());
        }
    }

    private void btnUbahStatusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUbahStatusActionPerformed
        pindahCard("cardUbahStatus");
    }// GEN-LAST:event_btnUbahStatusActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLaporanActionPerformed
        LaporanPemesananJadwal lp = new LaporanPemesananJadwal(lapangan);
        lp.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_btnLaporanActionPerformed

    private void btnJadwalTujuhActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalTujuhActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalTujuhActionPerformed

    private void btnJadwalDelapanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalDelapanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalDelapanActionPerformed

    private void btnJadwalSembilanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalSembilanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalSembilanActionPerformed

    private void btnJadwalSepuluhActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalSepuluhActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalSepuluhActionPerformed

    private void btnJadwalSebelasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalSebelasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalSebelasActionPerformed

    private void btnJadwalDuabelasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalDuabelasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalDuabelasActionPerformed

    private void btnJadwalTigabelasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalTigabelasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalTigabelasActionPerformed

    private void btnJadwalEmpatbelasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalEmpatbelasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalEmpatbelasActionPerformed

    private void btnJadwalLimabelasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalLimabelasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalLimabelasActionPerformed

    private void btnJadwalEnambelasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalEnambelasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalEnambelasActionPerformed

    private void btnJadwalTujuhbelasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalTujuhbelasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalTujuhbelasActionPerformed

    private void btnJadwalDelapanbelasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalDelapanbelasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalDelapanbelasActionPerformed

    private void btnJadwalSembilanbelasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalSembilanbelasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalSembilanbelasActionPerformed

    private void btnJadwalDuapuluhActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalDuapuluhActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalDuapuluhActionPerformed

    private void btnJadwalDuapuluhSatuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalDuapuluhSatuActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalDuapuluhSatuActionPerformed

    private void btnJadwalDuapuluhDuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalDuapuluhDuaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalDuapuluhDuaActionPerformed

    private void btnJadwalDuapuluhTigaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnJadwalDuapuluhTigaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnJadwalDuapuluhTigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardLapangan.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardLapangan.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardLapangan.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardLapangan.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaLapangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuka;
    private javax.swing.JToggleButton btnJadwalDelapan;
    private javax.swing.JToggleButton btnJadwalDelapanbelas;
    private javax.swing.JToggleButton btnJadwalDuabelas;
    private javax.swing.JToggleButton btnJadwalDuapuluh;
    private javax.swing.JToggleButton btnJadwalDuapuluhDua;
    private javax.swing.JToggleButton btnJadwalDuapuluhSatu;
    private javax.swing.JToggleButton btnJadwalDuapuluhTiga;
    private javax.swing.JToggleButton btnJadwalEmpatbelas;
    private javax.swing.JToggleButton btnJadwalEnambelas;
    private javax.swing.JToggleButton btnJadwalLimabelas;
    private javax.swing.JToggleButton btnJadwalSebelas;
    private javax.swing.JToggleButton btnJadwalSembilan;
    private javax.swing.JToggleButton btnJadwalSembilanbelas;
    private javax.swing.JToggleButton btnJadwalSepuluh;
    private javax.swing.JToggleButton btnJadwalTigabelas;
    private javax.swing.JToggleButton btnJadwalTujuh;
    private javax.swing.JToggleButton btnJadwalTujuhbelas;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnMaintenance;
    private javax.swing.JButton btnMatikanJadwal;
    private javax.swing.JButton btnNonaktifkanJadwal;
    private javax.swing.JButton btnTutup;
    private javax.swing.JButton btnUbahStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel judul;
    private javax.swing.JPanel judul2;
    private javax.swing.JLabel labelJadwalYangDipilih;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelKelolaLapangan;
    private javax.swing.JPanel panelLaporan;
    private javax.swing.JPanel panelMatikanJadwal;
    private javax.swing.JPanel panelUbahStatusLapangan;
    private com.github.lgooddatepicker.components.DatePicker tanggal;
    private javax.swing.JTextField txtAlasan;
    // End of variables declaration//GEN-END:variables
}
