/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MainClass.Jadwal;
import MainClass.Pengguna;
import ClassDAO.*;
import MainClass.Pembayaran;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Axioo Pongo
 */
public class PembayaranLangganan extends javax.swing.JFrame {

    private Pengguna pengguna;
    private buyLangganan parrent;
    private String tipe;
    private String statusPembayaran = "idle";
    private double harga;
    private LocalDate tanggal;
    private int KodePembayaran;
    private DAOLangganan daolang = new DAOLangganan();
    
    public PembayaranLangganan(Pengguna pengguna, String tipe, buyLangganan parrent) {
        initComponents();
        this.pengguna = pengguna;
        this.tipe = tipe;
        this.KodePembayaran = generateKodePembayaran();
        this.tanggal = LocalDate.now();
        this.parrent = parrent;
        this.harga = daolang.LoadSomeById(tipe).getHarga();
        setFrame();
    }
    
    private void setFrame() {
        JudulPemesanan.setText("Pemesanan Langganan "+tipe);
        KodePembayaranLabel.setText(String.format("Kode Pembayaran : %d",KodePembayaran));
        EmailLabel.setText("Email Pengguna : "+pengguna.getEmail());
        UsernameLabel.setText("Username : "+pengguna.getUsername());
        LanggananLabel.setText("Jenis Langganan : "+this.tipe);
        Tanggallabel.setText("Tanggal Pemesanan : "+this.tanggal.toString());
        hargalabel.setText("Harga : Rp. "+this.harga);
        
    }
    
    
    private int generateKodePembayaran() {
        int randomNum = 10000+((int)(Math.random() * 90000));
        return randomNum;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        LanggananLabel = new javax.swing.JLabel();
        Tanggallabel = new javax.swing.JLabel();
        hargalabel = new javax.swing.JLabel();
        JudulPemesanan = new javax.swing.JLabel();
        KodePembayaranLabel = new javax.swing.JLabel();
        bayarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        UsernameLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UsernameLabel.setText("Username : xxxxxxxxx");

        EmailLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailLabel.setText("Email : xxxxxxxxx@xxx");

        LanggananLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LanggananLabel.setText("Langganan : ");

        Tanggallabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Tanggallabel.setText("Tanggal pemesanan : ");

        hargalabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        hargalabel.setText("Harga total : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LanggananLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hargalabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tanggallabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LanggananLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tanggallabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hargalabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        JudulPemesanan.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        JudulPemesanan.setForeground(new java.awt.Color(255, 255, 255));
        JudulPemesanan.setText("Pembayaran Langganan xxxx");

        KodePembayaranLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        KodePembayaranLabel.setText("Kode Pembayaran : xxxxxxx");

        bayarBtn.setText("Bayar");
        bayarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JudulPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KodePembayaranLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bayarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(JudulPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(KodePembayaranLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bayarBtn)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bayarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBtnActionPerformed
        //tes
        TransferPengguna tf = new TransferPengguna();
        tf.setVisible(true);
        tf.setLocationRelativeTo(null);
        tf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Thread thread = new Thread(() -> {
            while(true){
                if(tf.isVisible()) {
                    System.out.println("Checking");
                }
                if(!tf.isVisible()){
                    statusPembayaran = cekPembayaran(tf.getKode(),tf.getNominal());
                    System.out.println("status tf : "+statusPembayaran);
                    
                }
                
                if(statusPembayaran.equals("sukses")){
                    String tempStatus = statusPembayaran;
                    statusPembayaran = "idle";
                    System.out.println("testing");
                    JOptionPane.showMessageDialog(null,
                    "Pemesanan Berhasil",
                    "Information",
                    JOptionPane.INFORMATION_MESSAGE);
                    this.parrent.prosesUpgrade(this.tipe);
                    this.dispose();
                    break;
                } else if(statusPembayaran.equals("kurang")) {
                    statusPembayaran = "idle";
                    JOptionPane.showMessageDialog(null,
                    "Jumlah yang kamu transfer tidak mencukupi untuk membayar tagihan.",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
                    tf.resetField();
                    tf.setVisible(true);
                    
                } else if(statusPembayaran.equals("salah")){
                    statusPembayaran = "idle";
                    JOptionPane.showMessageDialog(null,
                    "Kode Pembayaran yang kamu masukkan, tidak dapat dikenali.",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
                    tf.resetField();
                    tf.setVisible(true);
                }
            }
        });
        thread.start();
        
    }//GEN-LAST:event_bayarBtnActionPerformed

    private String cekPembayaran(String kode, String nominal) {
        int kodepembayaran = Integer.parseInt(kode);
        double Nominal = Double.parseDouble(nominal);
        
        if(kodepembayaran==this.KodePembayaran) {
            if(Nominal >= this.harga) {
                return "sukses";
            } else {
                return "kurang";
            }
        } else {
            return "salah";
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel JudulPemesanan;
    private javax.swing.JLabel KodePembayaranLabel;
    private javax.swing.JLabel LanggananLabel;
    private javax.swing.JLabel Tanggallabel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JButton bayarBtn;
    private javax.swing.JLabel hargalabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
