package GUI;


import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author benja
 */
public class pilihLapangan extends javax.swing.JFrame {

    /**
     * Creates new form pilihLapangan
     */
    public pilihLapangan() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("jButton1");
        jButton1.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(76, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton2);

        jButton3.setText("jButton3");
        jButton3.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton3);

        jButton4.setText("jButton4");
        jButton4.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton4.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton4.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton4);

        jButton5.setText("jButton5");
        jButton5.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton5.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton5);

        jButton6.setText("jButton6");
        jButton6.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton6.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton6.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton6);

        jButton7.setText("jButton7");
        jButton7.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton7.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton7.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton7);

        jButton8.setText("jButton2");
        jButton8.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton8.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton8.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton8);

        jButton9.setText("jButton3");
        jButton9.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton9.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton9.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton9);

        jButton10.setText("jButton4");
        jButton10.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton10.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton10.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton10);

        jButton11.setText("jButton7");
        jButton11.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton11.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton11.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton11);

        jButton12.setText("jButton6");
        jButton12.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton12.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton12.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton12);

        jButton13.setText("jButton5");
        jButton13.setMaximumSize(new java.awt.Dimension(508, 50));
        jButton13.setMinimumSize(new java.awt.Dimension(76, 50));
        jButton13.setPreferredSize(new java.awt.Dimension(76, 50));
        jPanel1.add(jButton13);

        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Montserrat Medium", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pilih Lapangan");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Urutkan Berdasarkan:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Harga", "Ketersediaan", "Nama" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
public static void main(String[] args) {
    try {
        UIManager.setLookAndFeel(new FlatLightLaf());
        FlatLightLaf.setup();
        UIManager.put("Button.arc", 20);
    } catch (Exception ex) {
        System.err.println("Failed to initialize LaF");
    }

    new pilihLapangan().setVisible(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
