/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ClassDAO.DAOPengguna;
import MainClass.Pengguna;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bani
 */
public class ProfilePanel extends javax.swing.JFrame {
    private Pengguna penggunaSaatIni;
    private final DAOPengguna daoPengguna;
    private final String idPengguna;

    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel(String id_Pengguna) {
        this.idPengguna = id_Pengguna;
        this.daoPengguna = new DAOPengguna();
        initComponents();
        loadUserData();
        setLocationRelativeTo(null);
    }

    private void loadUserData() {
        try {
            penggunaSaatIni = daoPengguna.LoadSomeById(idPengguna);
            if (penggunaSaatIni != null) {
                jLabel1.setText("Profile " + penggunaSaatIni.getUserName());
                UsernameEdited.setText(penggunaSaatIni.getUserName());
                EmailEdited.setText(penggunaSaatIni.getEmail());
                NoHpEdited.setText(penggunaSaatIni.getNo_telp()); // Fixed to match Pengguna class field
                JenisLanggananEdited.setText(penggunaSaatIni.getJenis_langganan());
            } else {
                // Handle case where pengguna is not found
                UsernameEdited.setText("Not Found");
                EmailEdited.setText("Not Found");
                NoHpEdited.setText("Not Found");
                JenisLanggananEdited.setText("Not Found");
            }
        } catch (Exception e) {
            Logger.getLogger(ProfilePanel.class.getName()).log(Level.SEVERE, "Error loading user data", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EmailEdited = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UsernameEdited = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NoHpEdited = new javax.swing.JLabel();
        JenisLanggananEdited = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROFILE X");

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14));
        jLabel2.setText("Username :");

        EmailEdited.setFont(new java.awt.Font("Poppins", 1, 14));
        EmailEdited.setText("Email :");

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14));
        jLabel4.setText("No HP :");

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14));
        jLabel5.setText("Jenis Langganan :");

        UsernameEdited.setFont(new java.awt.Font("Poppins", 1, 14));
        UsernameEdited.setText("Username :");

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 14));
        jLabel7.setText("Email :");

        NoHpEdited.setFont(new java.awt.Font("Poppins", 1, 14));
        NoHpEdited.setText("No HP :");

        JenisLanggananEdited.setFont(new java.awt.Font("Poppins", 1, 14));
        JenisLanggananEdited.setText("Jenis Langganan :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JenisLanggananEdited)
                            .addComponent(NoHpEdited)
                            .addComponent(EmailEdited)
                            .addComponent(UsernameEdited))))
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UsernameEdited))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(EmailEdited))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NoHpEdited))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JenisLanggananEdited))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }
    // </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel EmailEdited;
    private javax.swing.JLabel JenisLanggananEdited;
    private javax.swing.JLabel NoHpEdited;
    private javax.swing.JLabel UsernameEdited;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}