/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ClassDAO.DAOUlasan;
import MainClass.Lapangan;
import MainClass.Pengguna;
import MainClass.Rating;
import MainClass.Ulasan;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class UlasanFrame extends javax.swing.JFrame {

    /**
     * Creates new form UlasanFrame
     */
    String namaLapangan;
    public UlasanFrame() {
        initComponents();
    }

    public UlasanFrame(String id_lapangan, String namaLapangan) {
        initComponents();
        this.namaLapangan = namaLapangan;
        loadLapanganReviews(id_lapangan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UlasanLabelEdited = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelUlasan = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        UlasanLabelEdited.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        UlasanLabelEdited.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UlasanLabelEdited.setText("Ulasan Lapangan xx");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        panelUlasan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelUlasanLayout = new javax.swing.GroupLayout(panelUlasan);
        panelUlasan.setLayout(panelUlasanLayout);
        panelUlasanLayout.setHorizontalGroup(
            panelUlasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        panelUlasanLayout.setVerticalGroup(
            panelUlasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelUlasan);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setLabel("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(UlasanLabelEdited, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UlasanLabelEdited)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void loadLapanganReviews(String id_lapangan) {
        List<Ulasan> ulasanList = new DAOUlasan().getUlasanByLapangan(id_lapangan);
        
        panelUlasan.removeAll();
        panelUlasan.setLayout(new BoxLayout(panelUlasan, BoxLayout.Y_AXIS));

        if (ulasanList != null && !ulasanList.isEmpty()) {
            UlasanLabelEdited.setText("Ulasan Lapangan " + this.namaLapangan);
            for (Ulasan ulasanItem : ulasanList) {
                JPanel ulasanPanel = new JPanel();
                ulasanPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
                ulasanPanel.setBackground(Color.WHITE);
                ulasanPanel.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                ulasanPanel.setMaximumSize(new Dimension(700, 60));

                String ulasanDetails = """
                        <html>
                            <p>Komen : %s</p>
                            <p>Rating : %s</p>
                        </html>
                        """.formatted(
                            ulasanItem.getKomen(),
                            Rating.fromInt(ulasanItem.getRating().toInt()).toString()
                        );
                JLabel ulasanLabel = new JLabel(ulasanDetails);
                ulasanLabel.setFont(new Font("Poppins", Font.PLAIN, 14));
                ulasanPanel.add(ulasanLabel);

                panelUlasan.add(ulasanPanel);
                panelUlasan.add(Box.createVerticalStrut(10));    
            }
        } else {
            JLabel kosong = new JLabel("Belum ada ulasan lapangan dari pengguna ini.");
            kosong.setFont(new Font("Poppins", Font.ITALIC, 14));
            panelUlasan.add(kosong);
        }

        panelUlasan.revalidate();
        panelUlasan.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UlasanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UlasanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UlasanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UlasanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UlasanFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UlasanLabelEdited;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelUlasan;
    // End of variables declaration//GEN-END:variables
}
